# Clase 2 — Semana 1: Introducción a Pandas 2  
**Autor:** Robert Moreno  

> **Objetivo:** Reforzar lectura de datos, tipos (`dtype`), estadísticos básicos, conteos, `unique/nunique`, y limpieza de strings con `.str`.

## 1) Preparación

Seguimos trabajando con **`personas.csv`**.

**Hints:**
- Guarda `personas.csv` en la **misma carpeta** que el notebook.
- En **Google Colab**, sube el archivo antes de leerlo.
- Si el separador no es coma, usa `sep=...` (por ejemplo `sep=";"`).

Se identificó que la **identificación** (tipo cédula) de Guayaquil puede **perder el 0 inicial** (por ejemplo `09...`) si Pandas la lee como número.
**Hint:**
- Usa el parámetro `dtype`:
  - `dtype={"identificacion": "string"}`  (recomendado)
  - o `dtype={"identificacion": str}`

In [1]:
# Tu solución aquí
import pandas as pd
df = pd.read_csv("personas.csv", 
                 sep = "|", 
                 dtype={"identificacion": "string"})
df.sample(10)

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email
34408,1346514118,SOFÍA MERA ORTEGA,34.0,162.6,139.8,f,480.00,Manta,2024-08-03,Maestria,sofia.mera.ortega@gmail.com
16412,0940732662,Andrea Rojas Herrera,36.0,184.4,204.2,m,519.03,Guayaquil,NaN,Tecnico,andrea.rojas.herrera@empresa.ec
23334,0941030330,lucía delgado molina,48.0,169.9,161.8,f,480.00,Guayaquil,"Jan 07, 2024",Primaria,lucia.delgado.molina@hotmail.com
27798,1011640305,Jose Alvarado Carrillo,42.0,178.8,176.7,f,626.76,Ibarra,09/10/2024,Secundaria,NaN
47593,1711076644,miguel molina espinoza,36.0,173.5,167.1,m,1354.85,Quito,14/01/2025,Maestria,miguel.molina.espinoza@outlook.com
48251,1725873101,CRISTIAN SALAZAR ROJAS,50.0,188.4,177.7,f,952.97,Quito,12/04/2025,Tecnico,NaN
18911,0942665712,JORGE QUINTERO CEDEÑO,35.0,175.1,179.7,M,480.00,Guayaquil,2025-09-14,Tecnico,NaN
20017,0931610331,ALEJANDRA TAPIA CHÁVEZ,41.0,165.0,149.7,f,605.66,Guayaquil,NaN,Universidad,NaN
39476,1213365396001,Carla Villamar Delgado,38.0,170.2,147.4,M,480.00,Quevedo,13/04/2023,Tecnico,carla.villamar.delgado@outlook.com
27198,1050284544,PAOLA CORNEJO GARCÍA,49.0,191.8,218.8,M,887.92,Ibarra,2024-08-07,Secundaria,NaN

## 3) Promedio de edad

**Ejercicio 3:** ¿Cuál es el **promedio de edad** de las personas?

**Nota:**
- Si hay nulos, `mean()` por defecto los ignora.

In [5]:
# Tu solución aquí
df["edad"]

0        31.0
1        39.0
2        31.0
3        39.0
4        28.0
         ...
55102    32.0
55103    44.0
55104    29.0
55105    30.0
55106    41.0
Name: edad, Length: 55107, dtype: float64

## 4) Salario mínimo, promedio y máximo

**Ejercicio 4:** Calcula:
- salario mínimo
- salario promedio
- salario máximo

**Hints:**
- `min()`, `mean()`, `max()`
- También puedes usar `describe()`

In [7]:
# Tu solución aquí
print("Salario mínimo:", df["salario"].min)

Salario mínimo: <bound method Series.min of 0         480.00
1         480.00
2         605.28
3         826.56
4        1090.22
          ...
55102     480.00
55103    1001.04
55104     704.34
55105     794.08
55106     720.60
Name: salario, Length: 55107, dtype: float64>

In [9]:
# Tu solución aquí
print("Salario promedio:", df["salario"].mean)

Salario promedio: <bound method Series.mean of 0         480.00
1         480.00
2         605.28
3         826.56
4        1090.22
          ...
55102     480.00
55103    1001.04
55104     704.34
55105     794.08
55106     720.60
Name: salario, Length: 55107, dtype: float64>

In [8]:
# Tu solución aquí
print("Salario máximo:", df["salario"].max)

Salario máximo: <bound method Series.max of 0         480.00
1         480.00
2         605.28
3         826.56
4        1090.22
          ...
55102     480.00
55103    1001.04
55104     704.34
55105     794.08
55106     720.60
Name: salario, Length: 55107, dtype: float64>

## 5) `unique()` y `nunique()`

**Ejercicio 5:** Practiquemos con estas columnas:

5.1) ¿Cuáles son los valores únicos de `ciudad`? (`unique()`)  

**Hints:**
- `df["col"].unique()`

In [12]:
# Tu solución aquí
print(df["ciudad"].unique())

<StringArray>
[       'Ambato',        'Cuenca',    'Esmeraldas',     'Guayaquil',
        'Ibarra',          'Loja',       'Machala',         'Manta',
    'Portoviejo',       'Quevedo',         'Quito',      'Riobamba',
       'Salinas', 'Santo Domingo']
Length: 14, dtype: str

# Tu solución aquí

5.2) ¿Cuántas ciudades diferentes hay? (`nunique()`)  

**Hints:**

- `df["col"].nunique()`

In [16]:
# Tu solución aquí
print(df["ciudad"].nunique())

14

5.3) Repite lo mismo para `nivel_educacion`.

In [17]:
# Tu solución aquí
print(df["nivel_educacion"].nunique())

5

## 6) Limpieza de strings con `.str`

En el dataset, `sexo` puede venir como `M, m, F, f` y `nombre` puede tener espacios extra y case inconsistente.

**Ejercicio 6:**
1) Actualice la columna `sexo` colocandola en mayúsculas usando `.str.upper()`

In [14]:
# Tu solución aquí
df["sexo"].str.upper

In [ ]:
# Tu solución aquí

2) Crea una columna `nombre_clean` aplicando:
   - `.str.strip()` para quitar espacios al inicio y final
   - `.str.title()` para formato de nombre

In [19]:
# Tu solución aquí
df["nombre_clean"] = df["nombre"].str.strip().str.title()
df.head()

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email,nombre_clean
0,1842222836,Paola Mera Rodriguez,31.0,166.4,141.8,F,480.00,Ambato,28/03/2023,Secundaria,NaN,Paola Mera Rodriguez
1,1829202652,isabela molina silva,39.0,167.8,166.2,m,480.00,Ambato,20/08/2025,Tecnico,isabela.molina.silva@gmail.com,Isabela Molina Silva
2,1801036961,Fernanda Reyes Benítez,31.0,177.4,195.7,m,605.28,Ambato,"Apr 05, 2025",Secundaria,NaN,Fernanda Reyes Benítez
3,1823588783,gustavo molina mera,39.0,169.4,166.7,F,826.56,Ambato,06/03/2025,Secundaria,NaN,Gustavo Molina Mera
4,1816160012001,Sebastián Torres Cruz,28.0,179.4,183.7,m,1090.22,Ambato,2024-07-12,Universidad,sebastian.torres.cruz@hotmail.com,Sebastián Torres Cruz

## 7) ¿Cuántos hombres y mujeres hay?

**Ejercicio 7:** Usa `.value_counts()` para contar cuántos hay de cada sexo (usa `sexo_clean`).

In [20]:
# Tu solución aquí
df["sexo"].value_counts()

sexo
M    14327
m    14211
F    13322
f    13247
Name: count, dtype: int64

## 8) ¿Qué porcentaje representa cada sexo?

**Ejercicio 8:** Usa `value_counts(normalize=True)` para obtener proporciones.  
Luego multiplícalo por 100 para porcentaje.

In [22]:
# Tu solución aquí
(df["sexo"].value_counts(normalize = True) * 100).round(2).astype(str)+"%"

sexo
M     26.0%
m    25.79%
F    24.17%
f    24.04%
Name: proportion, dtype: str

In [ ]:
# Tu solución aquí

## 9) Crear datasets separados: mujeres y hombres

**Ejercicio 9:** Crea:
- `df_mujeres` (solo mujeres)
- `df_hombres` (solo hombres)

**Hints:**
- Mujeres: `df[df["sexo"] == "F"]`
- Hombres: `df[df["sexo"] == "M"]`

In [ ]:
#df[condicion]

## 10) Promedio de altura de mujeres

**Ejercicio 10:** Calcula el promedio de `altura_cm` en `df_mujeres`.

**Hint:** `df_mujeres["altura_cm"].mean()`

In [ ]:
# Tu solución aquí

## 11) Promedio de altura de hombres

**Ejercicio 11:** Calcula el promedio de `altura_cm` en `df_hombres`.

In [ ]:
# Tu solución aquí

## 12) ¿Quién gana más: hombres o mujeres?

**Ejercicio 12:** Compara el salario promedio entre `df_hombres` y `df_mujeres`.


✅ Responde con un comentario: `# En promedio ganan más ...`

In [ ]:
# Tu solución aquí
# salario_prom_hombres = ...
# salario_prom_mujeres = ...

# Respuesta (comentario):
#

## 13) Reconocer nulos y valores duplicados
**Ejercicio 13.1:** Utilizando `.isna().sum()` encuentre la cantidad de valores nulos para cada columna

In [ ]:
# Tu solución aquí
df.isna().sum()

identificacion         0
nombre                 0
edad                1570
altura_cm              0
peso_lb                0
sexo                   0
salario                0
ciudad                 0
fecha_registro      3276
nivel_educacion        0
email              23057
dtype: int64

**Ejercicio 13.2:** Utilizando `.duplicated().sum()` encuentre la cantidad de filas duplicadas. De haberlas, elimínelas usando `.drop_duplicates()`

In [7]:
# Tu solución aquí
df.duplicated().sum()
df.duplicated(subset = ["identificacion", "ciudad"]).sum()

np.int64(1231)

## 14) Preguntas interesantes (solo escribirlas) 👀

**Ejercicio 14:** Revisa el dataset (columnas y lo que has observado) y propone **4 preguntas** de análisis que te parezcan interesantes.

📌 Importante:
- **Solo escribe las preguntas como comentarios**.
- No necesitas codificarlas todavía.
- Pueden ser preguntas de negocio, sociales o de calidad de datos.

Ejemplo (solo como idea):  
- ¿El salario cambia según el nivel de educación?

In [ ]:
#df.head()

In [ ]:
# Escribe aquí 4 preguntas interesantes (solo comentarios):
# 1)
# 2)
# 3)
# 4)

---  
### (Opcional)  
Si sientes que con los conocimientos adquiridos hasta el momento, puedes responder una o más preguntas, adelante c: